spring:
  application:
    name: gd-wms-outbound
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 192.168.0.190
    port: 6389


pagehelper:
  helperDialect: oracle
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  page-size-zero: true
mybatis:
  typeAliasesPackage: com.bpm.gd.wms.outbound.server.mapper
  mapperLocations: classpath:mapper/*/*.xml
  configuration:
    map-underscore-to-camel-case: true
rule:
  log:
    enable: false
  service-name: order案例服务
# 服务版本管理配置
info:
  build:
     artifact: '@project.artifactId@'
     version: '@project.version@'
     server-name: ${rule.service-name}
#日志输出mybatis里面的sql
logging:
  level:
    com.bpm.gd.wms.outbound.server.mapper: debug

